/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.CardLayout;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author stephanie
 */
public class Bank_MainPanel extends javax.swing.JPanel {
    
    private Connection conn;
    private JPanel container;
    private CardLayout layout;
    
    /**
     * Creates new form Bank_MainPanel
     */
    public Bank_MainPanel(JPanel container, CardLayout layout) {
        initComponents();
        this.container = container;
        this.layout = layout;
        initConnection();
        //this.setSize(834, 458);  // adjust size here  
        //this.setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }
    
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );
                    if (conn != null && !conn.isClosed()) {
                            JOptionPane.showMessageDialog(null, "Database Connected Successfully!");
                    }

            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CWBank = new javax.swing.JLabel();
        btnBank = new javax.swing.JButton();
        btnBranch = new javax.swing.JButton();
        btnLoan = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CWBank.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        CWBank.setText("Cathedral Ward Bank");
        add(CWBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 44, -1, -1));

        btnBank.setBackground(new java.awt.Color(102, 102, 102));
        btnBank.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btnBank.setText("Bank Information");
        btnBank.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBank.addActionListener(this::btnBankActionPerformed);
        add(btnBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 134, 166, 85));

        btnBranch.setBackground(new java.awt.Color(102, 102, 102));
        btnBranch.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btnBranch.setText("Branch Information");
        btnBranch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBranch.addActionListener(this::btnBranchActionPerformed);
        add(btnBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 134, 166, 85));

        btnLoan.setBackground(new java.awt.Color(102, 102, 102));
        btnLoan.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btnLoan.setText("Loan Details");
        btnLoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLoan.addActionListener(this::btnLoanActionPerformed);
        add(btnLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 134, 166, 85));

        btnCustomer.setBackground(new java.awt.Color(102, 102, 102));
        btnCustomer.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btnCustomer.setText("Customer Profile");
        btnCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomer.addActionListener(this::btnCustomerActionPerformed);
        add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 264, 166, 85));

        btnAccount.setBackground(new java.awt.Color(102, 102, 102));
        btnAccount.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        btnAccount.setText("Account Details");
        btnAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccount.addActionListener(this::btnAccountActionPerformed);
        add(btnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 264, 166, 85));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(this::btnExitActionPerformed);
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 399, 60, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankActionPerformed
        // TODO add your handling code here:
        layout.show(container, "bank");
    }//GEN-LAST:event_btnBankActionPerformed

    private void btnBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBranchActionPerformed
        // TODO add your handling code here:
        layout.show(container, "branch");
    }//GEN-LAST:event_btnBranchActionPerformed

    private void btnLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanActionPerformed
        // TODO add your handling code here:
        layout.show(container, "loan");
    }//GEN-LAST:event_btnLoanActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        layout.show(container, "customer");        
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        layout.show(container, "account");        
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
                int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? :o", "Exit System...",
                     JOptionPane.YES_NO_OPTION,
                     JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.YES_OPTION) {
                      JOptionPane.showMessageDialog(null, "You selected: Yes... Goodbye!");
                      JOptionPane.showMessageDialog(null, "Thank you for using the system! :*]");
                      System.exit(0);
        } else {
                JOptionPane.showMessageDialog(null, "You selected: No... YAY!");
        }    
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CWBank;
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnBank;
    private javax.swing.JButton btnBranch;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoan;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
