
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author stephanie
 */
public class BankPanel extends javax.swing.JPanel {

    private Connection conn;
    private JPanel container;
    private CardLayout layout;
    /**
     * Creates new form BankPanel
     */
    public BankPanel(JPanel container, CardLayout layout) {
        initComponents();
        this.container = container;
        this.layout = layout;
        initConnection();
    }
    
    private void searchBankCode() {
        String inputID = JOptionPane.showInputDialog("Enter Bank Code to search:");

        if (inputID == null || inputID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Bank Code.");
            return;
        }

        try {
            String sql = "SELECT * FROM search_bankcode(?)"; //wala pa
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, inputID);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JTextArea textArea = new JTextArea(
                    "Bank Found!\n\n" +
                    "Bank Code: " + rs.getString("code") +
                    "\nBank Name: " + rs.getString("bname") +
                    "\nAddress: " + rs.getString("address") 
                );

                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 250));

                JOptionPane.showMessageDialog(null, scrollPane, "Bank Details", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry! No record found.");
            }

            rs.close();
            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Bank Code.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
        }
    } 
        
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        BankInfoTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtbankcode = new javax.swing.JTextField();
        txtbankname = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        bankcode = new javax.swing.JLabel();
        bankname = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(834, 458));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(this::btnBackActionPerformed);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 408, 90, 30));

        BankInfoTitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        BankInfoTitle.setText("Bank Information");
        add(BankInfoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 44, -1, -1));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnSearch.setText("Search Bank Code");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 123, 130, 30));

        txtbankcode.setBackground(new java.awt.Color(204, 204, 204));
        txtbankcode.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtbankcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbankcode.addActionListener(this::txtbankcodeActionPerformed);
        add(txtbankcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 178, 385, 30));

        txtbankname.setBackground(new java.awt.Color(204, 204, 204));
        txtbankname.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtbankname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 233, 385, 30));

        txtadd.setBackground(new java.awt.Color(204, 204, 204));
        txtadd.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 288, 385, 30));

        bankcode.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        bankcode.setText("Bank Code");
        add(bankcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 179, -1, -1));

        bankname.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        bankname.setText("Bank Name");
        add(bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 234, -1, -1));

        add.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        add.setText("Address");
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 289, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 348, 60, 30));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 348, 60, 30));

        btnDel.setBackground(new java.awt.Color(102, 102, 102));
        btnDel.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDel.addActionListener(this::btnDelActionPerformed);
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 348, 60, 30));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(this::btnSaveActionPerformed);
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 408, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cgc.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, -20, 220, 430));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        layout.show(container, "menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchBankCode();        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (txtbankcode.getText() == null || txtbankcode.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a Branch Code.");
                return;
            }
            
            String sql = "UPDATE BANK SET bname=?, address=? WHERE code=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            // kunin values mula sa text fields
            pst.setString(1, txtbankname.getText());
            pst.setString(2, txtadd.getText());
            pst.setString(3, txtbankcode.getText()); // code is VARCHAR(10)

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Bank record updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No bank found with that Code.");
            }

            txtbankcode.setText("");
            txtbankname.setText("");
            txtadd.setText("");

            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Update failed: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(
            null,
            "Wait! Are you sure you want to clear all fields? :o",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            txtbankcode.setText("");
            txtbankname.setText("");
            txtadd.setText("");
            JOptionPane.showMessageDialog(null, "Items were cleared!");
        } else {
            JOptionPane.showMessageDialog(null, "Clear action canceled.");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtbankcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankcodeActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Delete this bank?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (txtbankcode.getText() == null || txtbankcode.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a Branch Code.");
                return;
            }
                String sql = "DELETE FROM bank WHERE code=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtbankcode.getText());

                int rowsDeleted = pst.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Bank code not found.");
                }
                
                txtbankcode.setText("");
                txtbankname.setText("");
                txtadd.setText("");

                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Delete failed!");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {                                        
            // TODO add your handling code here:
            
            if ((txtbankcode.getText().isEmpty()) || (txtbankname.getText().isEmpty()) || (txtadd.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Oops! All fields should have input!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            String sql = "INSERT INTO bank(code,bname,address) VALUES (?,?,?)";
            //JOptionPane.showMessageDialog(null, avail_notavail); Removed
            
            PreparedStatement pst = null;
            try {
                pst = conn.prepareStatement(sql);
            } catch (SQLException ex) {
                System.getLogger(BankPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            pst.setString(1, txtbankcode.getText());
            pst.setString(2, txtbankname.getText());
            pst.setString(3, txtadd.getText());
            pst.execute();  //to save in the database
            JOptionPane.showMessageDialog(null,"Saved successfully!");
            JOptionPane.showMessageDialog(null,"Thank you! <3");
        } catch (SQLException ex) {
            System.getLogger(BankPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
            //}              
            
                //txtbankcode.setText("");
                //txtbankname.setText("");
                //txtadd.setText("");
           
        //} catch (SQLException e) { 
            //JOptionPane.showMessageDialog(null, "Save failed ;3"); 
            //e.printStackTrace(System.err); 
        //} 
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankInfoTitle;
    private javax.swing.JLabel add;
    private javax.swing.JLabel bankcode;
    private javax.swing.JLabel bankname;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtbankcode;
    private javax.swing.JTextField txtbankname;
    // End of variables declaration//GEN-END:variables
}
