/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author stephanie
 */
public class BranchPanel extends javax.swing.JPanel {
    
    private Connection conn;
    private JPanel container;
    private CardLayout layout;  

    /**
     * Creates new form BranchPanel
     */
    public BranchPanel(JPanel container, CardLayout layout) {
        initComponents();
        this.container = container;
        this.layout = layout;
        initConnection();
    }
    
    private void searchBranchNo() {
        String inputID = JOptionPane.showInputDialog("Enter Branch No. to search:");

        if (inputID == null || inputID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Branch Number.");
            return;
        }

        try {
            String sql = "SELECT * FROM search_bankbranch(?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(inputID)); // branchno is INT

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JTextArea textArea = new JTextArea(
                    "Bank Branch Found!\n\n" +
                    "Branch Number: " + rs.getInt("branchno") +
                    "\nAddress: " + rs.getString("addr") +
                    "\nBank Code: " + rs.getString("code")
                );

                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 250));

                JOptionPane.showMessageDialog(null, scrollPane, "Bank Branch Details", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry! No record found.");
            }

            rs.close();
            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Bank Branch Number. Please enter a number.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }
        
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        BankBranchTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtbrno = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        txtbankcode = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        brname = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        bankcode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(this::btnBackActionPerformed);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 408, 90, 30));

        BankBranchTitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        BankBranchTitle.setText("Bank Branch Information");
        add(BankBranchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 44, -1, -1));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnSearch.setText("Search Branch No.");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 123, 130, 30));

        txtbrno.setBackground(new java.awt.Color(204, 204, 204));
        txtbrno.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtbrno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbrno.addActionListener(this::txtbrnoActionPerformed);
        add(txtbrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 178, 378, 30));

        txtadd.setBackground(new java.awt.Color(204, 204, 204));
        txtadd.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 233, 378, 30));

        txtbankcode.setBackground(new java.awt.Color(204, 204, 204));
        txtbankcode.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtbankcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbankcode.addActionListener(this::txtbankcodeActionPerformed);
        add(txtbankcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 288, 378, 30));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 348, 60, 30));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 348, 60, 30));

        btnDel.setBackground(new java.awt.Color(102, 102, 102));
        btnDel.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDel.addActionListener(this::btnDelActionPerformed);
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 348, 60, 30));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(this::btnSaveActionPerformed);
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 408, 60, 30));

        brname.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        brname.setText("Branch Number");
        add(brname, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 179, -1, -1));

        add.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        add.setText("Address");
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 234, -1, -1));

        bankcode.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        bankcode.setText("Bank Code");
        add(bankcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 289, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cgc.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, -30, 220, 460));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchBranchNo();                
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtbrnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrnoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        layout.show(container, "menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtbankcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankcodeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(
            null,
            "Wait! Are you sure you want to clear all fields? :o",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            txtbrno.setText("");
            txtadd.setText("");
            txtbankcode.setText("");
            JOptionPane.showMessageDialog(null, "Items were cleared!");
        } else {
            JOptionPane.showMessageDialog(null, "Clear action canceled.");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    try {

                String sql = "UPDATE bank_branch SET addr=?, code=? WHERE branchno=?";                
                PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, txtadd.getText());                  
                    pst.setString(2, txtbankcode.getText());              
                    pst.setInt(3, Integer.parseInt(txtbrno.getText()));   


                int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(null, "Record updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "No record found with that Branch Number.");
                }
                
                txtbrno.setText("");
                txtadd.setText("");
                txtbankcode.setText("");
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Update failed: " + e.getMessage());
                e.printStackTrace(System.err);
            } 
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Delete this branch?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (txtbrno.getText() == null || txtbrno.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter a Branch Number.");
                    return;
                }

                String sql = "DELETE FROM bank_branch WHERE branchno=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(txtbrno.getText())); // branchno is INT

                int rowsDeleted = pst.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Branch number not found.");
                }

                txtbrno.setText("");
                txtadd.setText("");
                txtbankcode.setText("");

                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Delete failed: " + e.getMessage());
                e.printStackTrace(System.err);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Branch Number. Please enter a number.");
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {                                        
        if (txtbrno.getText().trim().isEmpty() || 
            txtadd.getText().trim().isEmpty() || 
            txtbankcode.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Oops! All fields should have input!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "INSERT INTO bank_branch(branchno, addr, code) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(txtbrno.getText())); // branchno is INT
        pst.setString(2, txtadd.getText());                 // addr
        pst.setString(3, txtbankcode.getText());            // code

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Saved successfully!");
        JOptionPane.showMessageDialog(null, "Thank you! <3");

        txtbrno.setText("");
        txtadd.setText("");
        txtbankcode.setText("");

        pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Branch Number. Please enter a number.");
        } catch (SQLException e) { 
            JOptionPane.showMessageDialog(null, "Save failed: " + e.getMessage()); 
            e.printStackTrace(System.err); 
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankBranchTitle;
    private javax.swing.JLabel add;
    private javax.swing.JLabel bankcode;
    private javax.swing.JLabel brname;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtbankcode;
    private javax.swing.JTextField txtbrno;
    // End of variables declaration//GEN-END:variables
}
