/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author stephanie
 */
public class CustomerPanel extends javax.swing.JPanel {
    
    private Connection conn;
    private JPanel container;
    private CardLayout layout;     

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel(JPanel container, CardLayout layout) {
        initComponents();
        this.container = container;
        this.layout = layout;
        //this.setSize(834, 735); // adjust size here 
        initConnection();
        
    }
    
    private void searchAccountNo() {
        String inputID = JOptionPane.showInputDialog("Enter Account No. to search:");

        if (inputID == null || inputID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Account Number.");
            return;
        }

        try {
            String sql = null;
            //String sql = "SELECT * FROM search_customerdetails(?)"; //wala pa
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(inputID));

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JTextArea textArea = new JTextArea(
                    "Customer Found!\n\n" +
                    "Last Name: " + rs.getString("lname") +
                    "\nFirst Name: " + rs.getString("fname") +
                    "\nMiddle Name: " + rs.getString("mname") +
                    "\nPhone Number: " + rs.getString("phone") +
                    "\nAddress: " + rs.getString("c_addr") +
                    "\nStatus: " + rs.getString("cstatus") +
                    "\nAge: " + rs.getInt("age") +                        
                    "\nAccount Number: " + rs.getString("acctno") 
                        
                );

                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 250));

                JOptionPane.showMessageDialog(null, scrollPane, "Customer Details", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry! No record found.");
            }

            rs.close();
            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Bank Branch Number. Please enter a number.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
        }
    } 
    
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        CustInfoTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        single = new javax.swing.JRadioButton();
        married = new javax.swing.JRadioButton();
        widowed = new javax.swing.JRadioButton();
        txtage = new javax.swing.JTextField();
        txtaccno = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lname = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        accno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(this::btnBackActionPerformed);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 677, 90, 30));

        CustInfoTitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        CustInfoTitle.setText("Customer Information");
        add(CustInfoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 44, -1, -1));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnSearch.setText("Search Account No.");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 123, 135, 30));

        txtlname.setBackground(new java.awt.Color(204, 204, 204));
        txtlname.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtlname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtlname.addActionListener(this::txtlnameActionPerformed);
        add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 178, 380, 30));

        txtfname.setBackground(new java.awt.Color(204, 204, 204));
        txtfname.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 233, 380, 30));

        txtmname.setBackground(new java.awt.Color(204, 204, 204));
        txtmname.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtmname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 288, 380, 30));

        txtphoneno.setBackground(new java.awt.Color(204, 204, 204));
        txtphoneno.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtphoneno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 343, 380, 30));

        txtadd.setBackground(new java.awt.Color(204, 204, 204));
        txtadd.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 398, 380, 30));

        buttonGroup1.add(single);
        single.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        single.setText("Single");
        add(single, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 456, -1, -1));

        buttonGroup1.add(married);
        married.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        married.setText("Married");
        married.addActionListener(this::marriedActionPerformed);
        add(married, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 456, -1, -1));

        buttonGroup1.add(widowed);
        widowed.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        widowed.setText("Widowed");
        add(widowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 456, -1, -1));

        txtage.setBackground(new java.awt.Color(204, 204, 204));
        txtage.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 502, 380, 30));

        txtaccno.setBackground(new java.awt.Color(204, 204, 204));
        txtaccno.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtaccno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtaccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 557, 380, 30));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 617, 60, 30));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 617, 60, 30));

        btnDel.setBackground(new java.awt.Color(102, 102, 102));
        btnDel.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDel.addActionListener(this::btnDelActionPerformed);
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 617, 60, 30));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(this::btnSaveActionPerformed);
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 677, 60, 30));

        lname.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        lname.setText("Last Name");
        add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 185, -1, -1));

        fname.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        fname.setText("First Name");
        add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 234, -1, -1));

        mname.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        mname.setText("Middle Name");
        add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 289, -1, -1));

        phoneno.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        phoneno.setText("Phone Number");
        add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 344, -1, -1));

        add.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        add.setText("Address");
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 399, -1, -1));

        status.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        status.setText("Status");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 453, -1, -1));

        age.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        age.setText("Age");
        add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 503, -1, -1));

        accno.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        accno.setText("Account Number");
        add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 564, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cibg.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 730));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cgc.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 230, 400));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 370, 320));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankbg2.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 210, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void marriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marriedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        layout.show(container, "menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(
            null,
            "Wait! Are you sure you want to clear all fields? :o",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            txtlname.setText("");
            txtfname.setText("");
            txtmname.setText("");
            txtphoneno.setText("");
            txtadd.setText("");
            buttonGroup1.clearSelection();
            txtage.setText("");
            txtaccno.setText("");
            JOptionPane.showMessageDialog(null, "Items were cleared!");
        } else {
            JOptionPane.showMessageDialog(null, "Clear action canceled.");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (txtaccno.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Account number is required to update a record.");
                return;
            }

            String cstatus = null;
            if (single.isSelected()) {
                cstatus = "S"; // Single
            } else if (married.isSelected()) {
                cstatus = "M"; // Married
            } else if (widowed.isSelected()) {
                cstatus = "W"; // Widowed
            }

            String sql = "UPDATE customer SET lname=?, fname=?, mname=?, phone=?, c_addr=?, cstatus=?, age=? WHERE acctno=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtlname.getText());   
            pst.setString(2, txtfname.getText());   
            pst.setString(3, txtmname.getText());   
            pst.setString(4, txtphoneno.getText()); 
            pst.setString(5, txtadd.getText());     
            pst.setString(6, cstatus);              
            pst.setInt(7, Integer.parseInt(txtage.getText())); 
            pst.setString(8, txtaccno.getText());   

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Customer record updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No record found with that Account Number.");
            }

            txtlname.setText("");
            txtfname.setText("");
            txtmname.setText("");
            txtphoneno.setText("");
            txtadd.setText("");
            buttonGroup1.clearSelection();
            txtage.setText("");
            txtaccno.setText("");

            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Age. Please enter a number.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Update failed: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            null, 
            "Delete this customer?", 
            "Confirm", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (txtaccno.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter Account Number.");
                    return;
                }

                String sql = "DELETE FROM customer WHERE acctno=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtaccno.getText()); 

                int rowsDeleted = pst.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Customer deleted successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Account number not found.");
                }

                txtlname.setText("");
                txtfname.setText("");
                txtmname.setText("");
                txtphoneno.setText("");
                txtadd.setText("");
                buttonGroup1.clearSelection();
                txtage.setText("");
                txtaccno.setText("");

                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Delete failed: " + e.getMessage());
                e.printStackTrace(System.err);
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String cstatus = null;
            if (single.isSelected()) {
                cstatus = "S"; 
            } else if (married.isSelected()) {
                cstatus = "M"; 
            } else if (widowed.isSelected()) {
                cstatus = "W";
            }

            if (txtlname.getText().trim().isEmpty() || 
                txtfname.getText().trim().isEmpty() || 
                txtmname.getText().trim().isEmpty() || 
                txtphoneno.getText().trim().isEmpty() || 
                txtadd.getText().trim().isEmpty() || 
                txtage.getText().trim().isEmpty() || 
                txtaccno.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Oops! All fields should have input!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (cstatus == null) {
                int choice = JOptionPane.showConfirmDialog(
                    null,
                    "No status selected.\nDefault will be set to 'Single'. Continue?",
                    "Confirm",
                    JOptionPane.YES_NO_OPTION
                );

                if (choice != JOptionPane.YES_OPTION) {
                    return; 
                }
                cstatus = "S"; 
            }

            String sql = "INSERT INTO customer(lname, fname, mname, phone, c_addr, cstatus, age, acctno) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtlname.getText());
            pst.setString(2, txtfname.getText());
            pst.setString(3, txtmname.getText());
            pst.setString(4, txtphoneno.getText());
            pst.setString(5, txtadd.getText());
            pst.setString(6, cstatus);
            pst.setInt(7, Integer.parseInt(txtage.getText()));
            pst.setString(8, txtaccno.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Customer saved successfully!");
            JOptionPane.showMessageDialog(null, "Thank you! <3");

            txtlname.setText("");
            txtfname.setText("");
            txtmname.setText("");
            txtphoneno.setText("");
            txtadd.setText("");
            buttonGroup1.clearSelection();
            txtage.setText("");
            txtaccno.setText("");

            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Age. Please enter a number.");
        } catch (SQLException e) { 
            JOptionPane.showMessageDialog(null, "Save failed: " + e.getMessage()); 
            e.printStackTrace(System.err); 
        }    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String inputID = JOptionPane.showInputDialog("Enter Account No. to search:");

        if (inputID == null || inputID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Account Number.");
            return;
        }

        try {
            String sql = "SELECT * FROM search_customer(?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, inputID); 

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JTextArea textArea = new JTextArea(
                    "Customer Information Found!\n\n" +
                    "Customer No: " + rs.getInt("custno") +
                    "\nLast Name: " + rs.getString("lname") +
                    "\nFirst Name: " + rs.getString("fname") +
                    "\nMiddle Name: " + rs.getString("mname") +
                    "\nPhone: " + rs.getString("phone") +
                    "\nAddress: " + rs.getString("c_addr") +
                    "\nStatus: " + rs.getString("cstatus") +
                    "\nAge: " + rs.getInt("age") +
                    "\nAccount No: " + rs.getString("acctno")
                );

                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 300));

                JOptionPane.showMessageDialog(null, scrollPane, "Customer Details", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry! No record found.");
            }

            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustInfoTitle;
    private javax.swing.JLabel accno;
    private javax.swing.JLabel add;
    private javax.swing.JLabel age;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lname;
    private javax.swing.JRadioButton married;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel phoneno;
    private javax.swing.JRadioButton single;
    private javax.swing.JLabel status;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JRadioButton widowed;
    // End of variables declaration//GEN-END:variables
}
