/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author stephanie
 */
public class LoanPanel extends javax.swing.JPanel {
    
    private Connection conn;
    private JPanel container;
    private CardLayout layout;    

    /**
     * Creates new form LoanPanel
     */
    public LoanPanel(JPanel container, CardLayout layout) {
        initComponents();
        this.container = container;
        this.layout = layout;
        initConnection();
    }

    private void searchAccountNo() {
        String inputID = JOptionPane.showInputDialog("Enter Account No. to search:");

        if (inputID == null || inputID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Account Number.");
            return;
        }

        try {
            String sql = "SELECT * FROM loan WHERE acctno = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, inputID); // acctno is VARCHAR

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JTextArea textArea = new JTextArea(
                    "Loan Information Found!\n\n" +
                    "Loan Number: " + rs.getString("loanno") +
                    "\nAmount: " + rs.getDouble("amount") +
                    "\nAccount Type: " + rs.getString("acct_type") +
                    "\nAccount Number: " + rs.getString("acctno")
                );

                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setEditable(false);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 250));

                JOptionPane.showMessageDialog(null, scrollPane, "Loan Details", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Sorry! No record found.");
            }

            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Search failed: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }
    
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );

            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        LoanInfoTitle = new javax.swing.JLabel();
        txtlono = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtamount = new javax.swing.JTextField();
        rbsavings = new javax.swing.JRadioButton();
        rbtd = new javax.swing.JRadioButton();
        txtaccno = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lono = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        acctype = new javax.swing.JLabel();
        accno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(this::btnBackActionPerformed);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 457, 90, 30));

        LoanInfoTitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        LoanInfoTitle.setText("Loan Information");
        add(LoanInfoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 44, -1, -1));

        txtlono.setBackground(new java.awt.Color(204, 204, 204));
        txtlono.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtlono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtlono, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 178, 377, 30));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        btnSearch.setText("Search Account No.");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 123, 135, 30));

        txtamount.setBackground(new java.awt.Color(204, 204, 204));
        txtamount.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 233, 377, 30));

        buttonGroup1.add(rbsavings);
        rbsavings.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        rbsavings.setText("Savings");
        rbsavings.addActionListener(this::rbsavingsActionPerformed);
        add(rbsavings, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 291, -1, -1));

        buttonGroup1.add(rbtd);
        rbtd.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        rbtd.setText("Time Deposit");
        add(rbtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 291, -1, -1));

        txtaccno.setBackground(new java.awt.Color(204, 204, 204));
        txtaccno.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtaccno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtaccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 337, 377, 30));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 397, 60, 30));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(this::btnClearActionPerformed);
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 397, 60, 30));

        btnDel.setBackground(new java.awt.Color(102, 102, 102));
        btnDel.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDel.addActionListener(this::btnDelActionPerformed);
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 397, 60, 30));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Bell MT", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(this::btnSaveActionPerformed);
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 457, 60, 30));

        lono.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        lono.setText("Loan Number");
        add(lono, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 185, -1, -1));

        amount.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        amount.setText("Amount");
        add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 240, -1, -1));

        acctype.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        acctype.setText("Account Type");
        add(acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 288, -1, -1));

        accno.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        accno.setText("Account Number");
        add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 344, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libg.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cgc.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 220, 360));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libg.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        layout.show(container, "menu");        
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbsavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsavingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbsavingsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // Validation
            if (txtlono.getText().trim().isEmpty() || 
                txtamount.getText().trim().isEmpty() || 
                txtaccno.getText().trim().isEmpty() || 
                (!rbsavings.isSelected() && !rbtd.isSelected())) {

                JOptionPane.showMessageDialog(null, "Oops! All fields should have input!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String sql = "INSERT INTO loan(loanno, amount, acct_type, acctno) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtlono.getText());
            pst.setDouble(2, Double.parseDouble(txtamount.getText()));

            String acctType = "";
            if (rbsavings.isSelected()) {
                acctType = "Savings";
            } else if (rbtd.isSelected()) {
                acctType = "Time Deposit";
            }
            pst.setString(3, acctType);
            pst.setString(4, txtaccno.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Loan saved successfully!");
            JOptionPane.showMessageDialog(null, "Thank you! <3");

            txtlono.setText("");
            txtamount.setText("");
            buttonGroup1.clearSelection();            
            txtaccno.setText("");

            pst.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Amount. Please enter a number.");
        } catch (SQLException e) { 
            JOptionPane.showMessageDialog(null, "Save failed: " + e.getMessage()); 
            e.printStackTrace(System.err); 
        }         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(
            null,
            "Wait! Are you sure you want to clear all fields? :o",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            txtlono.setText("");
            txtamount.setText("");
            buttonGroup1.clearSelection();            
            txtaccno.setText("");
            JOptionPane.showMessageDialog(null, "Items were cleared!");
        } else {
            JOptionPane.showMessageDialog(null, "Clear action canceled.");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
                if (txtlono.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Loan Number is required to update a record.");
                    return;
                }

                String sql = "UPDATE loan SET amount=?, acct_type=?, acctno=? WHERE loanno=?";
                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setDouble(1, Double.parseDouble(txtamount.getText()));

                String acctType = "";
                if (rbsavings.isSelected()) {
                    acctType = "Savings";
                } else if (rbtd.isSelected()) {
                    acctType = "Time Deposit";
                }
                pst.setString(2, acctType);
                pst.setString(3, txtaccno.getText());
                pst.setString(4, txtlono.getText());

                int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(null, "Loan record updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "No loan found with that Loan Number.");
                }

                txtlono.setText("");
                txtamount.setText("");
                buttonGroup1.clearSelection();            
                txtaccno.setText("");

                pst.close();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Amount. Please enter a number.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Update failed: " + e.getMessage());
                e.printStackTrace(System.err);
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Delete this Loan?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String loanNo = txtlono.getText().trim();
                if (loanNo.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter Loan Number.");
                    return;
                }

                String sql = "DELETE FROM loan WHERE TRIM(UPPER(loanno)) = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, loanNo.toUpperCase());

                int rowsDeleted = pst.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Loan number not found.");
                }

                txtlono.setText("");
                txtamount.setText("");
                buttonGroup1.clearSelection();            
                txtaccno.setText("");

                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Delete failed: " + e.getMessage());
                e.printStackTrace(System.err);
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchAccountNo();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoanInfoTitle;
    private javax.swing.JLabel accno;
    private javax.swing.JLabel acctype;
    private javax.swing.JLabel amount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lono;
    private javax.swing.JRadioButton rbsavings;
    private javax.swing.JRadioButton rbtd;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtlono;
    // End of variables declaration//GEN-END:variables
}
