/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author stephanie
 */
public class MainMenu extends javax.swing.JFrame {
       
    Connection conn;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    
        CardLayout cardLayout;
    
    public MainMenu() {
        initComponents();
        
        //this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
        //this.setSize(834, 458); // adjust size here 
        //this.setLocationRelativeTo(null); // centers the window 
                
        mainPanel.setLayout(new CardLayout()); 
        cardLayout = (CardLayout) mainPanel.getLayout(); 
        
        Bank_MainPanel menu = new Bank_MainPanel(mainPanel, cardLayout); 
        //BankPanel bank = new BankPanel(); 
        BankPanel bank = new BankPanel(mainPanel, cardLayout);
        bank.setPreferredSize(new java.awt.Dimension(834, 497));        
        
        BranchPanel branch = new BranchPanel(mainPanel, cardLayout);
        branch.setPreferredSize(new java.awt.Dimension(834, 497));        
        
        LoanPanel loan = new LoanPanel(mainPanel, cardLayout);
        branch.setPreferredSize(new java.awt.Dimension(834, 507));        
        
        CustomerPanel customer = new CustomerPanel(mainPanel, cardLayout); 
        branch.setPreferredSize(new java.awt.Dimension(834, 730));                
        
        AccountPanel account = new AccountPanel(mainPanel, cardLayout); 
        branch.setPreferredSize(new java.awt.Dimension(834, 508));                        
        
        
        mainPanel.add(menu, "menu"); 
        mainPanel.add(bank, "bank"); 
        mainPanel.add(branch, "branch");
        mainPanel.add(loan, "loan");
        mainPanel.add(customer, "customer"); 
        mainPanel.add(account, "account"); 
        
        //cardLayout.show(mainPanel, "menu");
       //pack(); // resize frame to fit the "menu" panel
        //setLocationRelativeTo(null); // keep centered      
        showPanel("menu");
    }
    
    // Example method to switch panels dynamically
    public void showPanel(String panelName) {
        cardLayout.show(mainPanel, panelName);
        pack(); // resize frame to fit the selected panel
        setLocationRelativeTo(null); // re-center
    }
    
    private void initConnection() {
            try {
                    //String url = ("jdbc:postgresql://localhost:5432/Book_DB; create=true; password=iheartdata1004");
                    //conn = DriverManager.getConnection(url); Note: Alternative

                    conn = DriverManager.getConnection(
                            "jdbc:postgresql://localhost:5432/Bank_DB",
                            "postgres",
                            "iheartdata1004"
    );

            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed!");
                    e.printStackTrace(System.err);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
